### ISSUE TITLE
ModuleNotFoundError: No module named 'gdt.datasets.specter_dataset'

### ISSUE THREAD

**Issue by billy322** [malteos/scincl#1]
Hi, I have the following error when running "python cli_specter.py extract_triples spector/train.pkl spector/train_triples.csv", how can I solve it, thanks.

**Comment by billy322** [comment]
> Hi, I have the following error when running "python cli_specter.py extract_triples spector/train.pkl spector/train_triples.csv", how can I solve it, thanks.

Also, may I ask where I can get the "S2ORC_EMBEDDINGS" ? Thanks.

**Comment by malteos** [comment]
> Hi, I have the following error when running "python cli_specter.py extract_triples spector/train.pkl spector/train_triples.csv", how can I solve it, thanks.

Sorry, that file was not checked in but now it should be fixed.

**Comment by malteos** [comment]
> > Hi, I have the following error when running "python cli_specter.py extract_triples spector/train.pkl spector/train_triples.csv", how can I solve it, thanks.
> 
> Also, may I ask where I can get the "S2ORC_EMBEDDINGS" ? Thanks.

`S2ORC_EMBEDDINGS` are the citation graph embeddings from S2ORC. See https://github.com/malteos/scincl#citation-graph-embeddings

The trained embeddings are quite large (150GB) and currently I do not have any possibility to upload them somewhere. But I would be happy to upload them somewhere if you have the infrastructure for that.

**Comment by ronaldseoh** [comment]
https://github.com/malteos/scincl/blob/25c49766632724eb15854de0d35b4bc086767d72/cli_specter.py#L57

I think it should be just `gdt.datasets.specter` here instead of `specter_dataset`

**Comment by malteos** [comment]
Thanks, the import path is now fixed as well.

**Comment by malteos** [comment]
Citation embeddings are now avaiable as download:

#### Download citation embeddings

- Replicated SPECTER (w/ leakage): [Pretrained embeddings (H5; 150 GB)](https://static.openlegaldata.io/scincl/s2orc_with_specter_without_scidocs/embeddings_paper_id_0.v200.h5), [paper IDs (JSON)](https://static.openlegaldata.io/scincl/s2orc_with_specter_without_scidocs/entity_names_paper_id_0.json)
- Random S2ORC (w/o leakage): [Pretrained embeddings (H5; 150 GB)](https://static.openlegaldata.io/scincl/s2orc_without_scidocs/embeddings_paper_id_0.v200.h5), [paper IDs (JSON)](https://static.openlegaldata.io/scincl/s2orc_without_scidocs/entity_names_paper_id_0.json)
