### ISSUE TITLE
training data w/o leakage

### ISSUE THREAD

**Issue by ronaldseoh** [malteos/scincl#2]
Hi Malte,

Thank you so much for making all your experimental codes and data files publicly available!

Just to confirm, are the data files on the releases page the replicated SPECTER training data _with_ leakage? As long as it's not too much hassle for you, could you please upload the one without leakage as well? Thank you in advance!!

**Comment by malteos** [comment]
Thanks for asking. I've added another release for **without leakage**: https://github.com/malteos/scincl/releases/tag/0.1-wol
