### ISSUE TITLE
Issues about README step: Merge SciDocs-S2ORC mapping  (from S2 API) 

### ISSUE THREAD

**Issue by MIracleyin** [malteos/scincl#5]
Hi malteos, I am happy to see your work about SDR.
I want to rebuild your work, but I find an issue below:

```
# Merge SciDocs-S2ORC mappings (from S2 API) 
python cli_s2orc.py get_s2orc_scidocs_mappings \
    ${SPECTER_DIR}/id2paper.json,${SPECTER_DIR}/specter_train_source_papers/id2paper.json,${SCIDOCS_DIR}/scidocs_s2orc/id2paper.json \
    ${DATA_DIR}/scidocs_s2id_to_s2orc_paper_id.json \
    ${SPECTER_DIR}/s2id_to_s2orc_paper_id.json
```

I am confused about 3 id2paper.json that come from different DIR. I get **${SPECTER_DIR}/s2/id2paper.json**. But I have no idea about 
```
${SPECTER_DIR}/id2paper.json,${SPECTER_DIR}/specter_train_source_papers/id2paper.json,${SCIDOCS_DIR}/scidocs_s2orc/id2paper.json
```

I check out before steps, but I am sure all steps I am already finished. Please give me some suggestions about my issue.
Thank! I think SCINCL is an interesting work!

**Comment by malteos** [comment]
Hi @MIracleyin 

the script merges different ID mapping files (obtained from different sources e.g.  S2 API or S2ORC). You do not need to run this yourself but instead you just can download the final mapping files. See https://github.com/malteos/scincl/releases/tag/0.1

- SciDocs mapping: https://github.com/malteos/scincl/releases/download/0.1/scidocs__s2id_to_s2orc_paper_id.latest.json.gz
- SPECTER mapping https://github.com/malteos/scincl/releases/download/0.1/specter__s2id_to_s2orc_paper_id.json.gz

After downloading you need to adjust the `ID_MAPPINGS` variable:

```bash
export ID_MAPPINGS=<DOWNLOAD_DIR>/scidocs__s2id_to_s2orc_paper_id.latest.json.gz,<DOWNLOAD_DIR>/specter__s2id_to_s2orc_paper_id.json.gz
```

Let me know if this resolves your issue.

**Comment by MIracleyin** [comment]
Yeah. 
I think I can using your mapping files. But I want to try it on my own construct. 
Maybe I read your cli_{sth}.py details will be helpful?

**Comment by malteos** [comment]
Do you want to get the ID mapping for other papers? 

Then you can try to scrape the paper meta data from S2 API. The following scripts extract paper IDs from the SPECTER training data (given as CSV - here you could drop in your own IDs), and then download the metadata.

```
# extract ids
python cli_triples.py extract_ids_from_triples ${SPECTER_DIR}/train_triples.csv ${SPECTER_DIR}/s2 s2_ids.csv query_s2_ids.csv

# query papers
python s2_scraper.py get_from_ids ${SPECTER_DIR}/s2/query_s2_ids.csv ${SPECTER_DIR}/s2 --save_every=1000

# all ids (NOT recommended, would take approx. 250 hrs - we did not do this for the paper)
python s2_scraper.py get_from_ids ${SPECTER_DIR}/s2/s2_ids.csv ${SPECTER_DIR}/s2 --save_every=1000
```

The scraper script stores the paper data in a JSON dictionary (ID => paper data). To get the ID mapping file you just need to reformat the JSON into source ID => target ID (e.g., S2API ID => S2ORC ID).

**Comment by MIracleyin** [comment]
Yes, I  have finished this step. And I get  
```
${SPECTER_DIR}/s2/id2error.json id2paper.json query_s2_ids.csv s2_ids.csv
```
But at this step **"merges different ID mapping files"** , I want to build on my own. I think there have three different id2paper.json.

```
{SPECTER_DIR}/id2paper.json,${SPECTER_DIR}/specter_train_source_papers/id2paper.json,${SCIDOCS_DIR}/scidocs_s2orc/id2paper.json
```
I find the repo and I am not know how to get those files.

Thanks for your help!

**Comment by malteos** [comment]
You can merge an arbitrary number of ID mappings. For my experiments, I just had three files (based on title matching, S2 API, and S2ORC PDF hashes). If you have only one source of ID mappings there is no need to merge. Then you can skip this step.

**Comment by MIracleyin** [comment]
Okay! I get your means! Thanks for your help! 
Have a nice day!
