### ISSUE TITLE
Memory need about Training corpus and graph embeddings

### ISSUE THREAD

**Issue by MIracleyin** [malteos/scincl#7]
Hi, @malteos

I follow your work but am stuck in memory-consuming.

First, I want to replicate SPECTER data (with leakage and without leakage), but I always fail in "Out of memory" that I check out by journalctl;

Second, I want to get graph embeddings as you do, but I still can't train on my service. In GPU, I got a "CudaError: out of memory", In CPU, I got a "Bus error (core dumped)".

My service has 100GB of memory and one RTX A5000. I read your paper about experiment machines without memory capacity in there.

Please give me some advice for the experiment platform so I can reproduce your work and have future work. 

BTW I think it is interesting in the area of Scientific Document Representation.

**Comment by malteos** [comment]
I cannot give you exact numbers because I ran the experiments on a cluster with changing compute nodes but each node had at least 200GB of memory available. You could probably reduce the memory requirement by a lot if you do not load the whole citation graph at once but instead in smaller chunks.

**Comment by MIracleyin** [comment]
Sorry, I reply so late. And thanks for your advice.
Yes, I put the citation graph into the database (such as clickhouse). But memory for graph training is still a problem. Maybe I need a larger RAM for this work.
Thank you again, have a nice day!
