### ISSUE TITLE
KNN efficiency on S2ORC graph

### ISSUE THREAD

**Issue by jaredcthomas** [malteos/scincl#8]
In your paper, you say that "the KNN strategy is implemented with FAISS using a flat index (exhaustive search) and takes less than 30min for indexing and retrieval". How did you achieve this speed with a flat index containing 52 M vectors?

**Comment by malteos** [comment]
KNN is not performed on the full S2ORC but only on the pool of candidate papers (~680k papers). The candidate papers come from SPECTER's training corpus (see Appendix C).

> The SciNCL triplets are generated based on the citation graph embeddings of the same 680,967 unique papers IDs, i.e, the FAISS index contains only these papers and not the remaining S2ORC papers.

**Comment by jaredcthomas** [comment]
I see. I want to replicate your process on a different corpus of a similar size to S2ORC. I am worried that a random sample of ~680k papers will have sufficiently different citation behavior from the curated SPECTER set that I cannot use your k+ and k- parameters. I'll have to measure collisions in my sample.
