### ISSUE TITLE
SciNCL for Text Classification

### ISSUE THREAD

**Issue by jd-coderepos** [malteos/scincl#9]
Hello,

many thanks for this great resource.

Could you advice a usage starter code of SciNCL for text classification with Transformers library? I wanted to train an encoder model for the text classification task.

**Comment by malteos** [comment]
You could try something like this:

```python
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("malteos/scincl")
```

However, SciNCL is trained to produce embeddings and that might make it suboptimal compared to vanilla language models (e.g., SciBERT). Instead, you could use the SciNCL embeddings and put them directly into a classifier such as SVM (without fine-tuning the model).
